from enum import Enum


class JobType(str, Enum):
    COMPILE = "COMPILE"
    RENDER_IMAGE = "RENDER_IMAGE"
    RENDER_VIDEO = "RENDER_VIDEO"
    RENDER_AUDIO = "RENDER_AUDIO"
    MERGE = "MERGE"
    QA = "QA"
    DELIVERY = "DELIVERY"
    CALLBACK = "CALLBACK"


class JobStatus(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    WAITING_RETRY = "WAITING_RETRY"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"
    STALE = "STALE"
    DEAD_LETTERED = "DEAD_LETTERED"


class AttemptType(str, Enum):
    PRIMARY = "PRIMARY"
    RETRY = "RETRY"
    INFRA_RERUN = "INFRA_RERUN"
    RECOVERY = "RECOVERY"
    MANUAL_RETRY = "MANUAL_RETRY"


class AttemptStatus(str, Enum):
    CREATED = "CREATED"
    CLAIMED = "CLAIMED"
    STARTED = "STARTED"
    PROVIDER_RUNNING = "PROVIDER_RUNNING"
    ARTIFACT_COLLECTING = "ARTIFACT_COLLECTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"
    STALE = "STALE"


class LeaseStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
